version: '3'
services:
    golden-raspberry-awards:
        container_name: golden-raspberry-awards
        build:
            dockerfile: Dockerfile
        volumes:
            - ./:/app:delegated
            - /app/node_modules
        ports:
            - 5000:4200


